---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: helloworld-prod
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.4
spec:
  releaseName: helloworld-prod
  chart:
    git: git@github.com:tsd1668/gitops-helm
    path: charts/helloworld
    ref: master
  values:
    image: tsd1668/hello_world:10
    replicaCount: 1
