# Default values for helloworld

replicaCount: 1

image: tsd1668/hello_world:7
imagePullPolicy: IfNotPresent

service:
  type: LoadBalancer
  externalPort: 8000
  containerPort: 8080
  nodePort: 31198

# Heapster or metrics-server add-on required
hpa:
  enabled: false
  maxReplicas: 2
  # average total CPU usage per pod (1-100)
  cpu: 10m
  # average memory usage per pod (100Mi-1Gi)
  memory:
  # average http requests per second per pod (k8s-prometheus-adapter)
  requests:

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - helloworld.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
  requests:
    cpu: 10m
    memory: 16Mi

nodeSelector: {}

tolerations: []

affinity: {}

logLevel: debug
